[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-frontend"
version = "0.1.0"
dependencies = [
    "streamlit",
    "httpx",
    "orjson",
]
